services:
  db:
    image: mysql:8.0
    container_name: zentime-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: zentime
    restart: always
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: